In [212]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder,OneHotEncoder
import pickle

In [213]:
data = pd.read_csv('Churn_Modelling.csv')
data.head()

   RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [214]:
data = data.drop(['RowNumber','CustomerId','Surname'],axis=1)

In [215]:
label_encoder_gender = LabelEncoder()
data['Gender'] = label_encoder_gender.fit_transform(data['Gender'])
data

      CreditScore Geography  Gender  ...  IsActiveMember  EstimatedSalary  Exited
0             619    France       0  ...               1        101348.88       1
1             608     Spain       0  ...               1        112542.58       0
2             502    France       0  ...               0        113931.57       1
3             699    France       0  ...               0         93826.63       0
4             850     Spain       0  ...               1         79084.10       0
...           ...       ...     ...  ...             ...              ...     ...
9995          771    France       1  ...               0         96270.64       0
9996          516    France       1  ...               1        101699.77       0
9997          709    France       0  ...               1         42085.58       1
9998          772   Germany       1  ...               0         92888.52       1
9999          792    France       0  ...               0         38190.78       0

[10000 rows x 11 columns]

In [216]:
onehot_encoder_geo = OneHotEncoder()
geo_encoder = onehot_encoder_geo.fit_transform(data[['Geography']])
geo_encoder

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 10000 stored elements and shape (10000, 3)>

In [217]:
geo_encoder.toarray()

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [218]:
onehot_encoder_geo.get_feature_names_out(['Geography'])

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [219]:
geo_encoded_df = pd.DataFrame(geo_encoder.toarray(),columns=onehot_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [220]:
data = pd.concat([data.drop('Geography',axis=1),geo_encoded_df],axis=1)
data.head()

   CreditScore  Gender  ...  Geography_Germany  Geography_Spain
0          619       0  ...                0.0              0.0
1          608       0  ...                0.0              1.0
2          502       0  ...                0.0              0.0
3          699       0  ...                0.0              0.0
4          850       0  ...                0.0              1.0

[5 rows x 13 columns]

In [221]:
with open('label_encoder_gender.pkl','wb') as file:
    pickle.dump(label_encoder_gender,file)

with open('onehot_encoder_geo.pkl','wb') as file:
    pickle.dump(onehot_encoder_geo,file)

In [222]:
X = data.drop('Exited',axis=1)
y = data['Exited']

In [223]:
x_train, x_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [224]:
x_train

      CreditScore  Gender  ...  Geography_Germany  Geography_Spain
9254          686       1  ...                0.0              0.0
1561          632       1  ...                1.0              0.0
1670          559       1  ...                0.0              1.0
6087          561       0  ...                0.0              0.0
6669          517       1  ...                0.0              0.0
...           ...     ...  ...                ...              ...
5734          768       1  ...                0.0              0.0
5191          682       0  ...                0.0              0.0
5390          735       0  ...                0.0              0.0
860           667       1  ...                0.0              0.0
7270          697       1  ...                1.0              0.0

[8000 rows x 12 columns]

In [225]:
x_test

      CreditScore  Gender  ...  Geography_Germany  Geography_Spain
6252          596       1  ...                1.0              0.0
4684          623       1  ...                0.0              0.0
1731          601       0  ...                0.0              1.0
4742          506       1  ...                1.0              0.0
4521          560       0  ...                0.0              1.0
...           ...     ...  ...                ...              ...
6412          602       0  ...                1.0              0.0
8285          609       1  ...                0.0              0.0
7853          730       0  ...                0.0              0.0
1095          692       1  ...                0.0              0.0
6929          628       1  ...                1.0              0.0

[2000 rows x 12 columns]

In [226]:
y_train

9254    0
1561    0
1670    1
6087    1
6669    1
       ..
5734    0
5191    0
5390    1
860     1
7270    0
Name: Exited, Length: 8000, dtype: int64

In [227]:
y_test

6252    0
4684    0
1731    0
4742    0
4521    0
       ..
6412    1
8285    0
7853    1
1095    1
6929    1
Name: Exited, Length: 2000, dtype: int64

In [228]:
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [229]:
x_train.shape[1]

12

In [230]:
with open('scaler.pkl','wb') as file:
    pickle.dump(sc,file)

ANN Implementation

In [231]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard
import datetime

In [232]:
model = Sequential([
    Dense(64,activation='relu',input_shape=(x_train.shape[1],)),
    Dense(32,activation='relu'),
    Dense(1,activation='sigmoid')
])

In [233]:
model.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_12 (Dense)            (None, 64)                832

 dense_13 (Dense)            (None, 32)                2080

 dense_14 (Dense)            (None, 1)                 33

=================================================================
Total params: 2945 (11.50 KB)
Trainable params: 2945 (11.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [234]:
opt = tf.keras.optimizers.Adam(learning_rate=0.01)
loss = tf.keras.losses.BinaryCrossentropy()

In [235]:
model.compile(optimizer=opt,loss=loss,metrics=['accuracy'])

In [236]:
log_dir = "logs/fit"+datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorflow_callback = TensorBoard(log_dir=log_dir,histogram_freq=1)

In [237]:
early_stopping_callback = EarlyStopping(monitor='val_loss',patience=10,restore_best_weights=True)

In [238]:
history = model.fit(
    x_train,y_train,validation_data=(x_test,y_test),epochs=100,
    callbacks = [tensorflow_callback,early_stopping_callback]
)

Epoch 1/100
250/250 [==============================] - 2s 4ms/step - loss: 0.3918 - accuracy: 0.8369 - val_loss: 0.3459 - val_accuracy: 0.8520
Epoch 2/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3534 - accuracy: 0.8546 - val_loss: 0.3422 - val_accuracy: 0.8560
Epoch 3/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3488 - accuracy: 0.8575 - val_loss: 0.3436 - val_accuracy: 0.8535
Epoch 4/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3426 - accuracy: 0.8614 - val_loss: 0.3388 - val_accuracy: 0.8585
Epoch 5/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3413 - accuracy: 0.8616 - val_loss: 0.3397 - val_accuracy: 0.8580
Epoch 6/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3357 - accuracy: 0.8636 - val_loss: 0.3476 - val_accuracy: 0.8575
Epoch 7/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3365 - accuracy: 0.8627 - val_loss: 0.3404 - val_accuracy: 0.8625
Epoch 8/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3340 - accuracy: 0.8626 - val_loss: 0.3538 - val_accuracy: 0.8545
Epoch 9/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3328 - accuracy: 0.8624 - val_loss: 0.3388 - val_accuracy: 0.8615
Epoch 10/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3301 - accuracy: 0.8599 - val_loss: 0.3565 - val_accuracy: 0.8620
Epoch 11/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3319 - accuracy: 0.8630 - val_loss: 0.3519 - val_accuracy: 0.8605
Epoch 12/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3281 - accuracy: 0.8625 - val_loss: 0.3422 - val_accuracy: 0.8650
Epoch 13/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3274 - accuracy: 0.8646 - val_loss: 0.3463 - val_accuracy: 0.8625
Epoch 14/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3245 - accuracy: 0.8671 - val_loss: 0.3515 - val_accuracy: 0.8595

In [239]:
model.save('model.h5')

/home/apmosys/Downloads/annclassification/venv/lib/python3.10/site-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(

In [240]:
%load_ext tensorboard

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard

In [243]:
%tensorboard --logdir logs/fit20260101-160736

Reusing TensorBoard on port 6008 (pid 1119682), started 0:00:03 ago. (Use '!kill 1119682' to kill it.)